### PR TITLE
Bump dependencies to NativeScript 6, and lazily get the Android Vibrator service

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
Hi!

I wanted to be able to create the Vibrator class on Android [before there was a context available](https://github.com/bazzite/nativescript-vibrate/blob/95b44d34b29f7b4edce827042a341ae092995309/src/vibrate.android.ts#L8), and that crashed my app.

This change supports that case, so making it more robust for silly folks like me using it in unintended ways.

Also: bump to NativeScript 6.

Thanks,
Eddy

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
It would be nice if this would not be auto-closed by a bot ;)

**Comment by juliomrqz** [comment]
Hello, @EddyVerbruggen. Thanks for your contribution :) This week a new version will be released.

**Comment by juliomrqz** [comment]
Hello, @EddyVerbruggen. You contribution is now available in the latest version ([v3.0.0](https://github.com/bazzite/nativescript-vibrate/releases/tag/v3.0.0)) 😀

**Comment by EddyVerbruggen** [comment]
@juliomrqz Awesome, thanks!

**Pull request merged**
